version: 2.1
executors:
  terratest_executor:
    docker:
      - image: sketchingdev/golang-terratest:latest
    working_directory: /go/src/app

jobs:
  test_s3_website:
    executor: terratest_executor
    steps:
      - checkout
      - run:
          name: Test S3 website
          command: |
            dep ensure -v
            go test -v -run TestS3WebsiteServesFile
          working_directory: s3_website/test/
  test_lambda_api_gateway:
    executor: terratest_executor
    steps:
      - checkout
      - run:
          name: Test lambda API gateway
          command: |
            dep ensure -v
            go test -v -run TestApiGatewayReturnsLambdaResponse
          working_directory: lambda_api_gateway/test/

workflows:
  version: 2
  tests:
    jobs:
      - test_s3_website
      - test_lambda_api_gateway
